// Code generated by mockery v2.53.6. DO NOT EDIT.

package transaction

import (
	context "context"

	dto "github.com/not-kamalesh/pismo-account/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionHandler is an autogenerated mock type for the TransactionHandler type
type MockTransactionHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockTransactionHandler) Create(ctx context.Context, req *dto.CreateTransactionRequest) (*dto.CreateTransactionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.CreateTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateTransactionRequest) (*dto.CreateTransactionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateTransactionRequest) *dto.CreateTransactionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateTransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateTransactionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTransactionHandler creates a new instance of MockTransactionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionHandler {
	mock := &MockTransactionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
