### Health Check
curl -X GET 'http://localhost:8080/health_check'

### Create Account
curl -sS -X POST 'http://localhost:8080/accounts' \
  -H 'Content-Type: application/json' \
  -d '{
    "msg_id": "4e01cff74f2585cbcdb38f66fb74573",
    "document_number": "123456789",
    "currency": "INR"
  }'

### Get Account by ID
curl -X GET 'http://localhost:8080/accounts/1?msgID=4e01cff74f2585cbcdb38f66fb74573'


### Create Transaction
curl -sS -X POST 'http://localhost:8080/transactions' \
  -H 'Content-Type: application/json' \
  -d '{"msg_id":"4e01cff74f2585cbcdb38f66fb74533","reference_id":"1e01cff74f2585cbcdb38f66fb74522","account_id":1, "operation_type_id": 4, "amount": 12.5}'