// Code generated by mockery v2.53.6. DO NOT EDIT.

package healthcheck

import (
	dto "github.com/not-kamalesh/pismo-account/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheck is an autogenerated mock type for the HealthCheckHandler type
type MockHealthCheck struct {
	mock.Mock
}

// HealthCheck provides a mock function with no fields
func (_m *MockHealthCheck) HealthCheck() *dto.HeathCheckResponse {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 *dto.HeathCheckResponse
	if rf, ok := ret.Get(0).(func() *dto.HeathCheckResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.HeathCheckResponse)
		}
	}

	return r0
}

// NewMockHealthCheck creates a new instance of MockHealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheck {
	mock := &MockHealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
