// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"

	dto "github.com/not-kamalesh/pismo-account/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountHandler is an autogenerated mock type for the AccountHandler type
type MockAccountHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockAccountHandler) Create(ctx context.Context, req *dto.CreateAccountRequest) (*dto.CreateAccountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.CreateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateAccountRequest) (*dto.CreateAccountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateAccountRequest) *dto.CreateAccountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, req
func (_m *MockAccountHandler) Get(ctx context.Context, req *dto.GetAccountRequest) (*dto.GetAccountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.GetAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetAccountRequest) (*dto.GetAccountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetAccountRequest) *dto.GetAccountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAccountHandler creates a new instance of MockAccountHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountHandler {
	mock := &MockAccountHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
