// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIAccountDAO is an autogenerated mock type for the IAccountDao type
type MockIAccountDAO struct {
	mock.Mock
}

// LoadByDocumentID provides a mock function with given fields: ctx, documentID
func (_m *MockIAccountDAO) LoadByDocumentID(ctx context.Context, documentID string) (*Account, error) {
	ret := _m.Called(ctx, documentID)

	if len(ret) == 0 {
		panic("no return value specified for LoadByDocumentID")
	}

	var r0 *Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Account, error)); ok {
		return rf(ctx, documentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Account); ok {
		r0 = rf(ctx, documentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadByID provides a mock function with given fields: ctx, accountID
func (_m *MockIAccountDAO) LoadByID(ctx context.Context, accountID int64) (*Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for LoadByID")
	}

	var r0 *Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, account
func (_m *MockIAccountDAO) Save(ctx context.Context, account *Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, accountID, status
func (_m *MockIAccountDAO) UpdateStatus(ctx context.Context, accountID int64, status string) error {
	ret := _m.Called(ctx, accountID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, accountID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockIAccountDAO creates a new instance of MockIAccountDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccountDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccountDAO {
	mock := &MockIAccountDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
