// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockITransactionDAO is an autogenerated mock type for the ITransactionDao type
type MockITransactionDAO struct {
	mock.Mock
}

// LoadByID provides a mock function with given fields: ctx, txnID
func (_m *MockITransactionDAO) LoadByID(ctx context.Context, txnID int64) (*Transaction, error) {
	ret := _m.Called(ctx, txnID)

	if len(ret) == 0 {
		panic("no return value specified for LoadByID")
	}

	var r0 *Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*Transaction, error)); ok {
		return rf(ctx, txnID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *Transaction); ok {
		r0 = rf(ctx, txnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, txnID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadByReferenceID provides a mock function with given fields: ctx, referenceID
func (_m *MockITransactionDAO) LoadByReferenceID(ctx context.Context, referenceID string) (*Transaction, error) {
	ret := _m.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for LoadByReferenceID")
	}

	var r0 *Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Transaction, error)); ok {
		return rf(ctx, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Transaction); ok {
		r0 = rf(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, txn
func (_m *MockITransactionDAO) Save(ctx context.Context, txn *Transaction) error {
	ret := _m.Called(ctx, txn)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Transaction) error); ok {
		r0 = rf(ctx, txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockITransactionDAO creates a new instance of MockITransactionDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionDAO {
	mock := &MockITransactionDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
