// Code generated by mockery v2.53.6. DO NOT EDIT.

package idempotencymgr

import mock "github.com/stretchr/testify/mock"

// MockIdempotencyMgr is an autogenerated mock type for the IdempotencyMgr type
type MockIdempotencyMgr struct {
	mock.Mock
}

// Execute provides a mock function with given fields: idempotencyKey, reqHash, handler
func (_m *MockIdempotencyMgr) Execute(idempotencyKey string, reqHash string, handler func() (interface{}, error)) (interface{}, error) {
	ret := _m.Called(idempotencyKey, reqHash, handler)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, func() (interface{}, error)) (interface{}, error)); ok {
		return rf(idempotencyKey, reqHash, handler)
	}
	if rf, ok := ret.Get(0).(func(string, string, func() (interface{}, error)) interface{}); ok {
		r0 = rf(idempotencyKey, reqHash, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, func() (interface{}, error)) error); ok {
		r1 = rf(idempotencyKey, reqHash, handler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIdempotencyMgr creates a new instance of MockIdempotencyMgr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyMgr(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyMgr {
	mock := &MockIdempotencyMgr{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
